language: node_js
node_js:
- 8.0.0
- 8.1.1
- 8.5.0
script:
- npm test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: yobrave@outlook.com
  api_key:
    secure: ZBbhBBFZ0mOvIhuXZwmK87h7JnwPAkEP88qaBx7jELHdos0r7O7G0F6Tb+Zfw7UWM2aJPXrMthH28rsbpr3zGX0Y3qD5VmfyeGWSZd+UimEmEYpQpJ1rilpynkMLpbBeultapN1bN4ZWGwDYsyoXNC4Y/lfleq+ZKE0O80oBqu8M1EXN1QJrCnV7lIz7R+FRk/EP3jo0LZ0ZBAWuhSbJ4JWzliD41NCJVanoT1qj//3+NXEgKCOPc2lvG31AhYDCj0C0/34MY1woS8laVEY5qA3fGUljktob2edcv1+VThZ8rP7yYKiKVmdd6mJpkDEBxAm8zR1FKg19Il1wo/20F2e/41wcaHch8WNXJWHXSaduXzK2VE5obsRTkwWL5WRddmdSsRuL3yu8W79wrMEh48oJXWHEP05dDAPxr7tmjEJke68fIOjdeAERU3V7hgSohjEgHLDRG1O7OskFX+FuUC5tDh+fYjVF0LgduR8OyLspXZgBwy2+Z0GyGaIhgVMGPsxZJkenXC0G8YMqzbqdakfBtEQrW8zXMSfa+FcsdbxnU6DW/BWNUFVCRfiabE453YuWh2/KzVSGKXmtIqqNkZpicDeZwsA691Ci6QwOIEx1ISo+aN8gCYO/U4PoSLDYfKxZvoBLNtvi/RNQxfAN9j0kIL3MRmKU3Fok0MsRNDI=
  on:
    branch: master
    tags: true
    repo: chinanf-boy/translate-js
